import "./globals.css";
import { Playfair_Display, Oregano, Poppins } from "next/font/google";

const playfair_display = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const oregano = Oregano({
  variable: "--font-oregano",
  subsets: ["latin"],
  weight: "400", 
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Birthday Card",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playfair_display.variable} ${oregano.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
